# class MyClass:
#     x = 5

# m = MyClass()
# print(m.x)    


# class Person:
#     def __init__(self,name,age):
#         self.name = name
#         self.age = age
# m = Person('Asilbek', 12)    
# print(m.age)
# print(m.name)

# # class person:
# #     def __init__(self,ism,yosh) -> None:
# #         self.name = ism
# #         self.age = yosh

# #     def __str__(self) -> str:
# #         return f'{self.name} {self.age}'    
# # m = person('Asilbek',12)
# # print(m)


# # class Person:
# #     def __init__(self,ism,yosh) -> None:
# #         self.name = ism
# #         self.age = yosh

# #     def myfunc(self):
# #         return f'Assalomu Aleykum {self.name}'
    
# # m = Person('Asilbek',12)
# # print(m.myfunc())

# class Person:
#     def __init__(self,ism,yosh) -> None:
#         self.name = ism
#         self.age = yosh

#     def myfunc(self):
#         return f'Assalomu Aleykum {2024-self.age}'
    
# m = Person('Asilbek',12)
# print(m.myfunc())


# class Kv:
#     def __init__(self,kv) -> None:
#         self.kv=kv
#     def sonlar(self):
#         return f'{self.kv**2}'
# a = Kv(l)
# print(a.sonlar())



# class Ded:
#     def __init__(self,ism) -> None:
#         self.age = ism
#     def halol(self):
#         return f'{self.age.title()}'
# d = Ded('asilbek') 
# print(d.halol())



# class uy:
#     def __init__(self, bir, ikki) -> None:
#         self.bir = bir
#         self.ikki = ikki
#     def h(self):
#         for i in range(self.bir, self.ikki):
#             print(i)
# b = uy(1,101) 
# b.h()      






# a = int(input())
# class Yu:
#     def __init__(self,yu) -> None:
#         self.yu = yu
#     def shu(self):
#         return f'{self.yu**2}'

# s = Yu(a)
# print(s.shu())















